# Generated by Django 2.1.4 on 2019-01-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20190111_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_capture',
            field=models.DateTimeField(),
        ),
    ]
