# Generated by Django 2.1.4 on 2019-01-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_user_last_capture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_capture',
            field=models.DateTimeField(default=None),
        ),
    ]
