# Generated by Django 2.1.4 on 2019-01-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_auto_20190111_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='type_chall',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
