# Generated by Django 2.1.4 on 2019-01-12 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0012_challenge_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='file_path',
            new_name='file_content',
        ),
    ]
