# Generated by Django 2.1.4 on 2019-01-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_auto_20190112_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.AddField(
            model_name='user',
            name='challenges_done',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
