# Generated by Django 2.2.4 on 2019-08-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0015_challenge_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='solved_by',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='challenges_done',
            field=models.TextField(default='[]'),
        ),
    ]
