image: python:latest 

stages:
        - build
        - code_style

build_job:
        stage: build
        before_script:
                - pip3 install django
        script:
                - cd decipher/
                - python3 scripts/generate_secret_key.py secretkey.txt
                - ./manage.py check

code_style_job:
        stage: code_style
        before_script:
                - pip3 install pylint
        script:
                - python3 -c "import this"
